Define a string variable with your name. Print characters of odd and even position of your name.

In [8]:
#Assigning name to variable My_name
My_name = "LIKITH"

#Creating two list for odd and even for storing
Odd_list = []
Even_list = []

#loop for finding out whether the position of the character is odd or even
for i in range(len(My_name)):
    if i % 2 == 0:
        Even_list.append(My_name[i])
    else:
        Odd_list.append(My_name[i])

#printing the odd and even list
print(f"The Even list of characters are: {Even_list}")
print(f"The Odd list of characters are: {Odd_list}")

The Even list of characters are: ['L', 'K', 'T']
The Odd list of characters are: ['I', 'I', 'H']


Create three variables named 'Student name', 'Course name', and 'EmailAddress'. Add 5 random values in these variables, where added values are not replaceable and print them.

In [6]:
#importing packages
import random

#actions to find 5 values of the variables
#chars = ascii_letters
Student_name = ("Student_A", "Student_B", "Student_C", "Student_D", "Student_E", "Student_F", "Student_G", "Student_H", "Student_I", "Student_J")
Course_name = ("Course_A", "Course_B", "Course_C", "Course_D", "Course_E", "Course_F", "Course_G", "Course_H", "Course_I", "Course_J")
Email_address = ("Gmail", "Hotmail", "Icloud", "Yahoo", "MSN", "Outlook", "msgme")

#printing the variables
Student_rand_names = random.sample(Student_name, 5)
print(Student_rand_names)
Course_rand_names = random.sample(Course_name, 5)
print(Course_rand_names)
Email_rand_names = random.sample(Email_address, 5)
print(Email_rand_names)

['Student_D', 'Student_E', 'Student_C', 'Student_J', 'Student_I']
['Course_H', 'Course_D', 'Course_C', 'Course_G', 'Course_B']
['Hotmail', 'msgme', 'MSN', 'Outlook', 'Icloud']


Create a dictionary variable with three keys, which are named same as the three variables created in the previous problem. Insert the previously created three variables values in the dictionary variable and print it.

In [9]:
#importing packages
from random import choice
from string import ascii_letters

#actions to find 5 values of the variables
chars = ascii_letters
Student_name = [''.join(choice(chars) for _ in range(5)) for _ in range(5)]
Course_name = [''.join(choice(chars) for _ in range(5)) for _ in range(5)]
Email_address = [''.join(choice(chars) for _ in range(5)) + "@gmail.com" for _ in range(5)]

#Storing the variables in a dictionary and printing
Uni_Dict = dict(Student_name = Student_name, Course_name = Course_name, Email_address = Email_address)
print(Uni_Dict)

{'Student_name': ['ttrih', 'DGXaj', 'MwfMy', 'liOeR', 'cdnBm'], 'Course_name': ['ZgXEc', 'GFAyR', 'qgJNo', 'sedZj', 'kVwEG'], 'Email_address': ['Xgogp@gmail.com', 'ZaiGW@gmail.com', 'nBCPb@gmail.com', 'odMFb@gmail.com', 'XFFEw@gmail.com']}


Define a string variable 'energy' and assign value either 'Fossil' or 'Renewable'. Print "Natural gas" if the value of energy variable is 'Fossil' otherwise print "solar power". What will your program print if energy='Biomass '?

In [4]:
print("Pick any value from the list below for Energy:\n1. Fossil\n2. Renewable\n3. Biomass")
energy = input()

if energy == 'Fossil':
    print("Natural Gas")
else:
    print("Solar power")

Pick any value from the list below for Energy:
1. Fossil
2. Renewable
3. Biomass
Solar power


Print all prime numbers between 0 and 100 separated by line.

In [6]:
print('Prime numbers between 1 and 100 are:')
 
for num in range(2,101):
   if num > 1:
       for i in range(2,num):
           if (num % i) == 0:
               break
       else:
           print(num)

Prime numbers between 1 and 100 are:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


Is it possible to break a loop before executing for the defined number of iterations? If yes, provide an example using While loop structure. Otherwise, explain your answer (why and how).

Answer: It is possible to end a loop before the predetermined amount of iterations. We can use the break statement in Python to accomplish this. The break statement will end the loop instantly and execute the statement that comes after it.

The Example below print the value of num until it reaches 5 and then breaks from the loop after reaching 5.

In [7]:
num = 1
while num <= 10:
    print(num)
    if num == 5:
        break
    num += 1

1
2
3
4
5


Create  functions named  'Addition', 'Multiplication', 'Division' and 'Subtraction'. These functions takes two input parameters say (x, y) and return (x+y),(x*y), (x/y) and (x-y). Call the function with (4,7) arguments and print the outputs

In [8]:
def Addition(x, y):
    return x + y

def Subtraction(x, y):
    return x - y

def Multiplication(x, y):
    return x * y

def Division(x, y):
    if (y != 0):
        return x / y
    else:
        print("Division by Zero is not valid")

print(Addition(4,7))
print(Subtraction(4,7))
print(Multiplication(4,7))
print(Division(4,7))

11
-3
28
0.5714285714285714


Create and display a 8x8 Identity matrix and multiply it with a 8x4 Random matrix.

In [8]:
import numpy as np

mat1 = np.identity(8, dtype=int)
print("The identity matrix is: \n", mat1)

mat2 = np.random.randint(10, size=(8,4))
print("\nThe random matrix is: \n", mat2)

mul_mat = np.matmul(mat1,mat2)
print("\nThe multiplied matrix is: \n", mul_mat)

The identity matrix is: 
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]

The random matrix is: 
 [[1 8 0 7]
 [5 1 3 0]
 [6 1 2 0]
 [5 2 2 4]
 [4 0 9 1]
 [8 8 2 6]
 [0 6 0 7]
 [3 8 9 4]]

The multiplied matrix is: 
 [[1 8 0 7]
 [5 1 3 0]
 [6 1 2 0]
 [5 2 2 4]
 [4 0 9 1]
 [8 8 2 6]
 [0 6 0 7]
 [3 8 9 4]]


Create a 8x9 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix?

Transpose matrix is basically where the row becomes column and column becomes row

In [25]:
import numpy

org_mat = numpy.random.randint(10, size=(8,9))
print("The original matrix is:")
print(org_mat,"\n\n")
transpose_mat = org_mat.transpose()
print("The transpose matrix is:")
print(transpose_mat)

The original matrix is:
[[9 2 2 1 3 8 5 6 7]
 [3 5 7 6 6 8 9 3 7]
 [9 4 5 9 4 3 0 6 0]
 [6 5 5 7 1 2 9 6 0]
 [7 4 2 2 3 5 2 2 0]
 [8 7 2 4 3 2 6 8 2]
 [4 0 0 0 4 7 6 5 1]
 [8 7 2 0 6 0 2 1 3]] 


The transpose matrix is:
[[9 3 9 6 7 8 4 8]
 [2 5 4 5 4 7 0 7]
 [2 7 5 5 2 2 0 2]
 [1 6 9 7 2 4 0 0]
 [3 6 4 1 3 3 4 6]
 [8 8 3 2 5 2 7 0]
 [5 9 0 9 2 6 6 2]
 [6 3 6 6 2 8 5 1]
 [7 7 0 0 0 2 1 3]]


Expport the "PedestrianCounting.csv" file as a matrix. The row of the matrix represents data point or instance and the column represents the variable or feature. Print the number of data instances and variables present in this dataset. Calculate mean of the third variable and deduct this mean from original values of the variable. Print both original and modified values of the variable.

In [2]:
import csv
import numpy

with open('/Users/likith/Library/Mobile Documents/com~apple~CloudDocs/Programming/SIT720 Machine Learning/pedestrian-counting-system-monthly-counts-per-hour.csv', 'r') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    data = list(reader)

csv_mat = numpy.array(data)

new_mat = numpy.delete(csv_mat, (0), axis = 0)

print("The number of data instance:", new_mat.shape[0])
print("The number of variables:", new_mat.shape[1])

new_mat[:, 2] = [float(str(i).replace(",", "")) for i in new_mat[:, 2]]

new_mat1 = new_mat[:, 2].astype(float)

mean = numpy.mean(new_mat1)

print("The mean value obtained is: ", mean)

mod_mat = new_mat1.copy()
mod_mat -= mean

print("\nThe original values of the 3rd variable is:")
print(new_mat1)

print("\nThe modified values of the 3rd variable is:")
print(mod_mat)

The number of data instance: 164316
The number of variables: 5
The mean value obtained is:  206.7159132403418

The original values of the 3rd variable is:
[25.  7. 13. ... 22. 56. 49.]

The modified values of the 3rd variable is:
[-181.71591324 -199.71591324 -193.71591324 ... -184.71591324 -150.71591324
 -157.71591324]
